// Ergonomic access to the backend contract types generated by `npm run codegen`
// into ./api.d.ts. These come straight from the backend's OpenAPI spec, so they
// are the source of truth — prefer `ApiSchema<'SomeDto'>` over hand-written
// response interfaces, and type API calls with them (e.g.
// `api.get<ApiSchema<'TenantResponseDto'>>(...)`) so contract drift fails at
// build time instead of as a runtime ZodError in the browser.
import type { components, paths } from './api';

export type ApiSchemas = components['schemas'];

/** A single named schema from the backend contract, e.g. ApiSchema<'TenantResponseDto'>. */
export type ApiSchema<K extends keyof ApiSchemas> = ApiSchemas[K];

/** The full generated `paths` map, for typing request/response by route when needed. */
export type ApiPaths = paths;
